  project: 'u2021014'
  
  input: '/mnt/picea/home/mshemirani/Git/nf-core-netseq/test_data/samplesheet.csv'
  
  # Genome reference
  genome: 'TAIR10'
  
  outdir: './test_results'

  # Fastp adapter reference
  adapter_fasta: '/mnt/picea/home/mshemirani/Git/nf-core-netseq/test_data/TrueSeq3-PE-custom.fa'
  
  # sektq parameters
  trim_beginning: 4
  trim_end: 4
  
  # star 
  star_ignore_sjdbgtf: False
  seq_platform: 'Illumina'
  seq_center: 'Peter Kindgren'
  
